version: '3.8'
services:
  app:
    container_name: news_webapi
    build: .
    networks:
      - news_webapi_network
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - uploads_data:/uploads
    ports:
      - "8000:5000"
    env_file:
      - .env

  db:
    image: mysql:8.0
    container_name: news_webapi_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3308:3306"
    networks:
      - news_webapi_network
    volumes:
      - mysql_data:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: news_webapi_phpmyadmin_app
    networks:
      - news_webapi_network
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_PORT: 3306
      UPLOAD_LIMIT: 64M
      MEMORY_LIMIT: 256M
    ports:
      - "8080:80" # Access phpMyAdmin via http://localhost:8080
    restart: unless-stopped

networks:
  news_webapi_network:

volumes:
  uploads_data:
  mysql_data: